### PR TITLE
Migration Telegram.Bot to version 17.0

### LINKED ISSUE #350: Migrate Telegram.Bot to v17
Telegram.Bot has a new major release. Now supporting [Bot API 5.4](https://core.telegram.org/bots/api#november-5-2021).

Migration Guide: https://telegrambots.github.io/book/Migration-Guide-to-Version-17.x.html

### PR DESCRIPTION
**Pull request by Jadhielv**
Closes #350

### CODE REVIEW

**Comment by nminaya** [comment]
@Jadhielv Nice work here. Although this migration screws up most of our unit tests because they turned all methods of `ITelegramClient` into extension methods 🥴

Give me some time to think what I can do with the unit tests.

**Comment by Jadhielv** [comment]
@nminaya Ok, go ahead

**Review by nminaya — APPROVED** [review]

**Comment by nminaya** [comment]
@Jadhielv Take a look at the changes I did and merge away if everything looks fine to you

**Comment by Jadhielv** [comment]
@nminaya LGTM.

**Pull request merged**
